-- Baseline snapshot of the live production schema (project qklwmgjhskqnfsidfsrr).
-- Captured 2026-07-04 via the Supabase Management API (pg_dump/db pull needed Docker,
-- unavailable on this machine); this file documents current state, not a fresh-DB replay.

create domain public.email_text as text
  constraint email_text_check check (value ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'::text);

-- provides moddatetime(), used by the two triggers below. (A bug in the
-- introspection query that captured this baseline -- tgrelid::regnamespace
-- is not a valid namespace cast -- originally missed both triggers
-- entirely; corrected once found in 20260704020200.)
create extension if not exists moddatetime with schema public;

create table public."admins" (
  "id" uuid not null,
  "created_at" timestamp with time zone default now() not null
);

alter table public."admins" add constraint "admins_pkey" PRIMARY KEY (id);
alter table public."admins" add constraint "admins_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public."admins" enable row level security;

create table public."employment_type" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "type" character varying not null,
  "active" boolean default true not null
);

alter table public."employment_type" add constraint "employment_type_pkey" PRIMARY KEY (id);
alter table public."employment_type" add constraint "employment_type_type_key" UNIQUE (type);

alter table public."employment_type" enable row level security;

create table public."membership_type" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "type" character varying not null,
  "description" character varying not null,
  "active" boolean default true not null,
  "PAID" boolean default true not null
);

alter table public."membership_type" add constraint "membership_type_pkey" PRIMARY KEY (id);
alter table public."membership_type" add constraint "membership_type_type_key" UNIQUE (type);

alter table public."membership_type" enable row level security;

create table public."membership_privilege" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "membership_type" character varying not null,
  "privilege" character varying not null,
  "view" boolean default false not null,
  "edit" boolean default false not null,
  "execute" boolean default false not null,
  "active" boolean default true not null
);

alter table public."membership_privilege" add constraint "membership_privilege_pkey" PRIMARY KEY (id);

CREATE INDEX idx_membership_privilege_type ON public.membership_privilege USING btree (membership_type);

alter table public."membership_privilege" enable row level security;

create table public."profiles" (
  "id" uuid not null,
  "email" public.email_text not null,
  "full_name" text not null,
  "phone_e164" text,
  "city" text,
  "country" text,
  "graduation_year" integer not null,
  "degree" text,
  "branch" text,
  "roll_number" text,
  "employment_type" text,
  "company" text,
  "designation" text,
  "avatar_url" text,
  "interests" text[] default '{}'::text[] not null,
  "onboarded" boolean default false not null,
  "is_public" boolean default true not null,
  "is_approved" boolean default false not null,
  "consent_terms_privacy" boolean default false not null,
  "consent_directory_visible" boolean default false not null,
  "consent_directory_show_contacts" boolean default false not null,
  "accepted_terms_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "gender" text,
  "company_url" character varying,
  "approved_by_email" character varying,
  "approved_date" timestamp with time zone,
  "status" text default 'PENDING'::text
);

alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table public."profiles" add constraint "profiles_email_key" UNIQUE (email);
alter table public."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public."profiles" enable row level security;

create trigger trg_profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.moddatetime('updated_at');

create table public."member_memberships" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "user_email" character varying not null,
  "membership_type" character varying not null,
  "start_date" timestamp with time zone not null,
  "end_date" timestamp with time zone,
  "membership_id" character varying,
  "Payment" real,
  "Mode" character varying,
  "Received_by" character varying,
  "Received_date" timestamp without time zone default now(),
  "params" text
);

alter table public."member_memberships" add constraint "member_memberships_pkey" PRIMARY KEY (id);
alter table public."member_memberships" add constraint "member_memberships_membership_id_key" UNIQUE (membership_id);

CREATE INDEX idx_member_memberships_start_date ON public.member_memberships USING btree (start_date);
CREATE INDEX idx_member_memberships_user_email ON public.member_memberships USING btree (user_email);

alter table public."member_memberships" enable row level security;

create table public."memoirs" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "email" character varying,
  "message" text not null,
  "show_on_main_page" boolean default false not null,
  "priority_seq" integer default 0 not null,
  "name" character varying,
  "batch" integer,
  "branch" character varying,
  "role_company" character varying,
  "date_approved" timestamp with time zone,
  "active" boolean default true
);

alter table public."memoirs" add constraint "memoirs_pkey" PRIMARY KEY (id);

alter table public."memoirs" enable row level security;

create table public."events" (
  "id" uuid default gen_random_uuid() not null,
  "title" text not null,
  "date" timestamp with time zone not null,
  "location" text,
  "href" text,
  "created_at" timestamp with time zone default now()
);

alter table public."events" add constraint "events_pkey" PRIMARY KEY (id);

alter table public."events" enable row level security;

create table public."jobs" (
  "id" uuid default gen_random_uuid() not null,
  "title" text not null,
  "company" text not null,
  "location" text,
  "employment_type" text,
  "experience_level" text,
  "apply_url" text not null,
  "has_alumni_referral" boolean default false not null,
  "referrer_id" uuid,
  "tags" text[] default '{}'::text[] not null,
  "posted_by" uuid,
  "status" text default 'published'::text not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

alter table public."jobs" add constraint "jobs_pkey" PRIMARY KEY (id);
alter table public."jobs" add constraint "jobs_referrer_id_fkey" FOREIGN KEY (referrer_id) REFERENCES profiles(id);
alter table public."jobs" add constraint "jobs_posted_by_fkey" FOREIGN KEY (posted_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public."jobs" add constraint "jobs_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text]));

alter table public."jobs" enable row level security;

create trigger trg_jobs_set_updated_at
  before update on public.jobs
  for each row execute function public.moddatetime('updated_at');

create table public."login_history" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "user_id" uuid not null,
  "user_email" text not null,
  "action" character varying not null
);

alter table public."login_history" add constraint "login_history_pkey" PRIMARY KEY (id);

CREATE INDEX idx_login_history_user_id_created_at ON public.login_history USING btree (user_id, created_at DESC);

alter table public."login_history" enable row level security;

create view public."user_signin_pivot_last_10_days" as
 SELECT lh.user_email,
    p.full_name,
    p.graduation_year,
    p.branch,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '00:00:00'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_0,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '1 day'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_1,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '2 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_2,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '3 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_3,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '4 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_4,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '5 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_5,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '6 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_6,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '7 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_7,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '8 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_8,
    count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '9 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS day_9,
    count(*) FILTER (WHERE ((lh.created_at >= (CURRENT_DATE - '9 days'::interval)) AND ((lh.action)::text = 'sign_in'::text))) AS total
   FROM (login_history lh
     JOIN profiles p ON ((lh.user_email = (p.email)::text)))
  GROUP BY lh.user_email, p.full_name, p.graduation_year, p.branch
  ORDER BY (count(*) FILTER (WHERE (((lh.created_at)::date = (CURRENT_DATE - '00:00:00'::interval)) AND ((lh.action)::text = 'sign_in'::text)))) DESC;

create or replace function public.app_is_active_admin(p_email text)
 returns boolean
 language sql
 security definer
 set search_path to 'public'
as $function$
  select exists (
    select 1
    from member_memberships m
    where m.user_email = p_email
      and upper(m.membership_type) in ('ADMIN_L1','ADMIN_L2')
      and (m.start_date is null or m.start_date <= now())
      and (m.end_date   is null or m.end_date   >= now())
  );
$function$;

create or replace function public.get_active_privileges(p_email text)
 returns table(membership_type text, privilege text, view boolean, edit boolean, execute boolean)
 language sql
 security definer
 set search_path to 'public'
as $function$
  select
    mp.membership_type,
    mp.privilege,
    mp.view,
    mp.edit,
    mp.execute
  from public.member_memberships mm
  join public.membership_type mt
    on mt.type = mm.membership_type
  join public.membership_privilege mp
    on mp.membership_type = mm.membership_type
  where
    mm.user_email = p_email
    and mt.active = true
    and mp.active = true
    and now() between mm.start_date and mm.end_date
$function$;

create or replace function public.get_user_privileges(_email text)
 returns table(privilege text, view boolean, edit boolean, execute boolean)
 language sql
 stable
as $function$
  select
    mp.privilege,
    bool_or(mp.view)    as view,
    bool_or(mp.edit)    as edit,
    bool_or(mp.execute) as execute
  from member_memberships mm
  join membership_type mt
    on mm.membership_type = mt.type
  join membership_privilege mp
    on mp.membership_type = mt.type
  where mm.user_email = _email
    and mt.active = true
    and mp.active = true
    and (mm.start_date is null or mm.start_date <= now())
    and (mm.end_date is null or mm.end_date >= now())
  group by mp.privilege;
$function$;

create or replace function public.has_privilege(caller_email text, privilege_name text)
 returns boolean
 language sql
 stable
as $function$
  select exists (
    select 1
    from public.member_memberships mm
    join public.membership_privilege mp on mm.membership_type = mp.membership_type
    where mm.user_email = caller_email
      and mp.privilege = privilege_name
      and mp.execute = true
      and mm.start_date <= now()
      and (mm.end_date is null or mm.end_date >= now())
  );
$function$;

create or replace function public.has_privilege_for_year(caller_email text, privilege_name text, target_year integer)
 returns boolean
 language plpgsql
 stable
as $function$
declare
  mm_row record;
  p jsonb;
  b text;
begin
  for mm_row in
    select mm.params::jsonb as params_json
    from public.member_memberships mm
    join public.membership_privilege mp on mm.membership_type = mp.membership_type
    where mm.user_email = caller_email
      and mp.privilege = privilege_name
      and mp.execute = true
      and mm.start_date <= now()
      and (mm.end_date is null or mm.end_date >= now())
  loop
    p := mm_row.params_json;
    if p is null then
      continue;
    end if;

    if (p -> 'batches') is not null then
      for b in select jsonb_array_elements_text(p -> 'batches') loop
        if b = target_year::text then
          return true;
        end if;
      end loop;
    end if;

    if (p ->> 'from') is not null and (p ->> 'to') is not null then
      if target_year >= (p ->> 'from')::int and target_year <= (p ->> 'to')::int then
        return true;
      end if;
    end if;
  end loop;

  return false;
end;
$function$;

create or replace function public.set_terms_if_null(p_user_id uuid)
 returns void
 language plpgsql
as $function$
begin
  update public.profiles
  set accepted_terms_at = now()
  where id = p_user_id and accepted_terms_at is null;
end;
$function$;

-- moddatetime() and set_updated_at() also exist in prod as generic trigger helpers,
-- but nothing attaches them (no triggers in this DB) and no app code sets updated_at
-- on writes -- profiles.updated_at/jobs.updated_at are effectively dead columns.
-- Left out of this baseline; worth a future ticket (wire a trigger, or drop the columns).

create policy "Admins can read self" on public."admins" as permissive for SELECT to authenticated
  using ((id = auth.uid()));
create policy "Service role manages admins" on public."admins" as permissive for ALL to service_role
  using (true)
  with check (true);
create policy "events are readable to all" on public."events" as permissive for SELECT to public
  using (true);
create policy "Admins manage jobs" on public."jobs" as permissive for ALL to authenticated
  using ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.id = auth.uid()))))
  with check ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.id = auth.uid()))));
create policy "Approved can insert jobs" on public."jobs" as permissive for INSERT to authenticated
  with check ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.is_approved))));
create policy "Approved can read jobs" on public."jobs" as permissive for SELECT to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.is_approved))));
create policy "Author can update own job" on public."jobs" as permissive for UPDATE to authenticated
  using ((posted_by = auth.uid()))
  with check ((posted_by = auth.uid()));
create policy "insert_own_login_history" on public."login_history" as permissive for INSERT to authenticated
  with check ((auth.uid() = user_id));
create policy "select_own_login_history" on public."login_history" as permissive for SELECT to authenticated
  using ((auth.uid() = user_id));
create policy "users_select_own_memberships" on public."member_memberships" as permissive for SELECT to public
  using (((user_email)::text = auth.email()));
create policy "authenticated_select_privileges" on public."membership_privilege" as permissive for SELECT to public
  using ((auth.role() = 'authenticated'::text));
create policy "Public can read approved memoirs" on public."memoirs" as permissive for SELECT to public
  using (((active = true) AND (date_approved IS NOT NULL)));
create policy "Admins full access profiles" on public."profiles" as permissive for ALL to authenticated
  using ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.id = auth.uid()))))
  with check ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.id = auth.uid()))));
create policy "Public directory reads" on public."profiles" as permissive for SELECT to public
  using ((is_approved AND is_public AND consent_directory_visible));
create policy "User can insert own profile" on public."profiles" as permissive for INSERT to authenticated
  with check ((auth.uid() = id));
create policy "User can read own profile" on public."profiles" as permissive for SELECT to authenticated
  using ((auth.uid() = id));
create policy "User can update own profile" on public."profiles" as permissive for UPDATE to authenticated
  using ((auth.uid() = id))
  with check ((auth.uid() = id));
create policy "profiles_update_approve_all" on public."profiles" as permissive for UPDATE to public
  using (has_privilege(auth.email(), 'APPROVE_ONBOARD_ALL'::text));
create policy "profiles_update_approve_batch" on public."profiles" as permissive for UPDATE to public
  using (((graduation_year IS NOT NULL) AND has_privilege_for_year(auth.email(), 'APPROVE_ONBOARD_BATCH'::text, graduation_year)));
create policy "profiles_update_combined" on public."profiles" as permissive for UPDATE to public
  using ((has_privilege(auth.email(), 'APPROVE_ONBOARD_ALL'::text) OR ((graduation_year IS NOT NULL) AND has_privilege_for_year(auth.email(), 'APPROVE_ONBOARD_BATCH'::text, graduation_year))));
